src/apps/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"


urlpatterns = [
    path("", views.settings_view, name="settings-home"),
    path("sessions/", views.session_settings_view, name="setting-sessions"),
    path("terms/", views.term_settings_view, name="setting-terms"),
    path("exam-sessions/", views.exam_session_view, name="setting-exam-sessions"),
    path("update-settings/", views.update_settings, name="settings-update"),
    path("fee-settings/", views.fee_settings, name="settings-fees"),
    path(
        "toggle-marks-uploads/",
        views.toggle_teacher_can_upload_marks_permission,
        name="toggle-marks-uploads",
    ),
]

src/apps/terms/urls.py
from django.urls import path

from . import views

app_name = "sessions"


urlpatterns = [
    path("create-session", views.create_academic_year, name="session-create"),
    path("edit-session/<int:pkid>/", views.edit_academic_year, name="session-edit"),
    path("mark-session-active/<int:pkid>/", views.mark_session_as_active, name="session-mark-active"),

    path("create-term", views.create_term_view, name="term-create"),
    path("edit-term/<int:pkid>/", views.edit_term_view, name="term-edit"),
    path("mark-term-active/<int:pkid>/", views.mark_term_as_active, name="term-mark-active"),

    path("create-exam-session/", views.add_exam_session_view, name="exam-session-add"),
    path("edit-exam-session/<int:pkid>/", views.edit_exam_session_view, name="exam-session-edit"),
    path("mark-exam-session/<int:pkid>/", views.mark_exam_session_as_current_view, name="exam-session-mark-active")
]

src/sms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import include, path

from apps.scelery.views import form_view
from apps.teachers import views
from apps.students.views import get_classes_by_department

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # local apps
    path("", include("apps.staff.urls", namespace="staff")),
    path("students/", include("apps.students.urls", namespace="students")),
    path("teachers/", include("apps.teachers.urls", namespace="teachers")),
    path("payments/", include("apps.fees.urls", namespace="fees")),
    path("settings/", include("apps.settings.urls", namespace="settings")),
    path("sessions/", include("apps.terms.urls", namespace="sessions")),
    path("reports/", include("apps.reports.urls", namespace="reports")),
    # Classes
    path("classes/", views.class_list_view, name="class-list"),
    path("add-class/", views.class_add_view, name="class-add"),
    path("edit/<int:pkid>/", views.class_edit_view, name="class-edit"),
    path("delete/<int:pkid>/", views.class_delete_view, name="class-delete"),
    path(
        "download-sample-class-upload/",
        views.download_sample_class_file,
        name="download-sample-class-upload",
    ),
    path(
        "upload-class-from-file",
        views.upload_classes_from_file,
        name="upload-class-from-file",
    ),
    # auth
    path("accounts/", include("apps.users.urls", namespace="users")),
    path(
        "password-reset-complete",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("attendance/", include("apps.attendance.urls", namespace="attendance")),
    path("leave/", include("apps.leave.urls", namespace="leave")),
    # testing
    path("form/", form_view, name="form"),
    path(
        "get-classes/",
        get_classes_by_department,
        name="get_classes_by_department",
    ),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/settings/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

from apps.common.models import TimeStampedUUIDModel


class Setting(TimeStampedUUIDModel):
    school_logo = models.FileField(
        verbose_name=_("Logo"), upload_to="settings", blank=True, null=True
    )
    school_favicon = models.FileField(
        verbose_name=_("Favicon"), upload_to="settings/", blank=True, null=True
    )
    school_name = models.CharField(
        verbose_name=_("School Name"), max_length=255, blank=True, null=True
    )
    currency = models.CharField(
        max_length=255,
        verbose_name=_("Currency"),
        help_text="Enter the currency you wish to appear on reciepts (CFA, XAF)",
        blank=True,
        null=True,
    )

    # School address information

    city = models.CharField(
        verbose_name=_("City"), max_length=255, blank=True, null=True
    )
    postal_code = models.CharField(
        verbose_name=_("Zip/Posttal Code"), max_length=255, blank=True, null=True
    )
    address1 = models.CharField(
        verbose_name=_("Address Line 1"), max_length=255, blank=True, null=True
    )
    address2 = models.CharField(
        verbose_name=_("Address Line 2"), max_length=255, blank=True, null=True
    )
    country = CountryField(
        verbose_name=_("Country"), default="CM", blank=False, null=False
    )

    motto = models.CharField(
        verbose_name=_("Motto"), max_length=255, blank=True, null=True
    )

    highest_upload_mark = models.IntegerField(
        verbose_name=_("Highest Marks Allowed for upload"),
        default=20,
        blank=True,
        null=True,
    )

    # Fees
    first_installment = models.DecimalField(
        max_digits=10, decimal_places=2, default=10000, blank=True, null=True
    )
    second_installment = models.DecimalField(
        max_digits=10, decimal_places=2, default=10000, blank=True, null=True
    )
    pta = models.DecimalField(
        max_digits=10, decimal_places=2, default=10000, blank=True, null=True
    )
    school_uniform = models.DecimalField(
        max_digits=10, decimal_places=2, default=10000, blank=True, null=True
    )
    next_opening_date = models.DateField(default=timezone.now)

    teacher_can_upload = models.BooleanField(default=False)

    @property
    def get_complete_fee(self):
        return self.first_installment + self.second_installment

src/apps/settings/views.py
from django.contrib import messages
from django.contrib.auth.models import Group, Permission
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import get_user_model

from apps.terms.models import AcademicYear, ExaminationSession, Term

from .models import Setting


User = get_user_model()


def settings_view(request):
    if request.method == "POST":
        # Check if settings already exist in the database
        setting = Setting.objects.all().first()
        if setting:
            messages.error(request, "Settings already initialized.")
            return redirect(reverse("settings:settings-home"))

        setting = Setting.objects.create()
        setting.save()

        # Create the different groups needed to run the system
        students_group, _ = Group.objects.get_or_create(name="students")
        teachers_group, _ = Group.objects.get_or_create(name="teachers")
        admin_group, _ = Group.objects.get_or_create(name="administrator")

        # Define the permissions to add
        student_permissions = [
            "change_studentprofile",
            "change_class",
            "view_subject",
            "view_reportcard",
            "view_studentprofile",
            "view_announcement",
        ]

        teacher_permissions = [
            "add_mark",
            "change_mark",
            "view_mark",
            "add_attendance",
            "change_attendance",
            "view_attendance",
            "view_announcement",
        ]

        admin_permissions = [
            "add_announcement",
            "change_announcement",
            "delete_announcement",
            "view_announcement",
            # admin profile
            "add_adminprofile",
            "change_adminprofile",
            "view_adminprofile",
            "delete_adminprofile",
            # sessions
            "add_session",
            "change_session",
            "view_session",
            "delete_session",
            # subjects
            "add_subject",
            "change_subject",
            "view_subject",
            "delete_subject",
            # Attendance
            "add_attendance",
            "change_attendance",
            "delete_attendance",
            "view_attendance",
            # Managring clasess
            "add_class",
            "change_class",
            "delete_class",
            "view_class",
            # Marks management
            "add_mark",
            "change_mark",
            "delete_mark",
            "view_mark",
            # Managing students
            "add_studentprofile",
            "change_studentprofile",
            "delete_studentprofile",
            "view_studentprofile",
            # Managring teacher profiles
            "add_teacherprofile",
            "change_teacherprofile",
            "delete_teacherprofile",
            "view_teacherprofile",
            # Session management
            "add_academicyear",
            "change_academicyear",
            "delete_academicyear",
            "view_academicyear",
            "add_examinationsession",
            "change_examinationsession",
            "delete_examinationsession",
            "view_examinationsession",
            # Term Management
            "add_term",
            "change_term",
            "delete_term",
            "view_term",
            # Fee manaagement
            "add_fee",
            "change_fee",
            "delete_fee",
            "view_fee",
            "add_feepaymenthistory",
            "change_feepaymenthistory",
            "delete_feepaymenthistory",
            "view_feepaymenthistory",
            # Reportcards
            "add_reportcard",
            "change_reportcard",
            "delete_reportcard",
            "view_reportcard",
        ]

        # Initialize message container
        message = ""

        # Add student permissions to the group
        for perm in student_permissions:
            try:
                permission = Permission.objects.get(codename=perm)
                students_group.permissions.add(permission)
                message += f'Permission "{perm}" added to group "students".\n'
            except Permission.DoesNotExist:
                message += f'Permission "{perm}" does not exist.\n'

        # Add teacher permissions to the group
        for perm in teacher_permissions:
            try:
                permission = Permission.objects.get(codename=perm)
                teachers_group.permissions.add(permission)
                message += f'Permission "{perm}" added to group "teachers".\n'
            except Permission.DoesNotExist:
                message += f'Permission "{perm}" does not exist.\n'

        # Add admin permissions to the group
        for perm in admin_permissions:
            try:
                permission = Permission.objects.get(codename=perm)
                admin_group.permissions.add(permission)
                message += f'Permission "{perm}" added to group "administrator".\n'
            except Permission.DoesNotExist:
                message += f'Permission "{perm}" does not exist.\n'

        # Create a default system hiden administrator account
        admin_user = User.objects.create_user(
            username="admin",
            email="admin@mail.com",
            first_name="Admin",
            last_name="Admin",
            password="nimda",
            is_superuser=True,
        )
        admin_user.save()
        # Flash success message
        messages.success(request, "Settings have been successfully initialized.\n")
        return redirect(reverse("settings:settings-home"))

    setting = Setting.objects.all().first()

    template_name = "settings/settings.html"
    context = {"section": "settings", "setting": setting}

    return render(request, template_name, context)


def fee_settings(request):
    setting = Setting.objects.all().first()
    if request.method == "POST":
        # get the data from the form
        first_installment = request.POST.get("first_installment")
        second_installment = request.POST.get("second_installment")
        pta = request.POST.get("pta")
        school_uniform = request.POST.get("school_uniform")
        print(first_installment, second_installment)
        # update fee payment information
        setting.first_installment = first_installment
        setting.second_installment = second_installment
        setting.pta = pta
        setting.school_uniform = school_uniform
        setting.save()
        messages.success(request, "Fee payment updated successfully")
        return redirect(reverse("settings:settings-fees"))
    template_name = "settings/fee-settings.html"
    context = {"section": "settings", "setting": setting}

    return render(request, template_name, context)


def update_settings(request):
    settings = Setting.objects.all()
    if len(settings) > 0:
        setting = settings.first()
    else:
        messages.error(request, "Settings have not yet been initialized.")
        return redirect(reverse("settings:settings-home"))

    if request.method == "POST":
        # extract the fields
        data = request.POST
        school_name = data.get("school_name")
        currency = data.get("currency")
        country = data.get("country")
        city = data.get("city")
        address1 = data.get("address1")
        address2 = data.get("address2")
        postal = data.get("postal_code")
        motto = data.get("motto")
        highest_upload_mark = data.get("highest_upload_mark")
        logo = request.FILES.get("logo")
        favicon = request.FILES.get("favicon")

        print("this is the highest mark ", highest_upload_mark)

        setting.school_name = school_name
        if currency:
            setting.currency = currency
        if country:
            setting.country = country
        if city:
            setting.city = city
        if address1:
            setting.address1 = address1
        if address2:
            setting.address2 = address2
        if postal:
            setting.postal_code = postal
        if motto:
            setting.motto = motto
        if highest_upload_mark:
            setting.highest_upload_mark = highest_upload_mark

        if logo:
            print("This is the logo", logo)
            setting.school_logo = logo
        if favicon:
            setting.school_favicon = favicon

        setting.save()

        messages.success(request, "Settings have been successfully updated")

        return redirect(reverse("settings:settings-home"))
    return redirect(reverse("settings:settings-home"))


def session_settings_view(request):

    sessions = AcademicYear.objects.all()
    current_session = sessions.filter(is_current=True).first()
    template_name = "settings/session-settings.html"
    context = {
        "section": "settings",
        "sessions": sessions,
        "current_session": current_session,
    }

    return render(request, template_name, context)


def term_settings_view(request):

    sessions = AcademicYear.objects.all()
    terms = Term.objects.all()

    current_session = sessions.filter(is_current=True).first()
    current_term = terms.filter(is_current=True).first()
    template_name = "settings/term-settings.html"
    context = {
        "section": "settings",
        "sessions": sessions,
        "terms": terms,
        "current_session": current_session,
        "current_term": current_term,
    }

    return render(request, template_name, context)


def exam_session_view(request):

    exam_sessions = ExaminationSession.objects.all()
    sessions = AcademicYear.objects.all()
    terms = Term.objects.all()

    current_session = sessions.filter(is_current=True).first()
    current_term = terms.filter(is_current=True).first()
    current_exam_session = ExaminationSession.objects.filter(is_current=True).first()

src/templates/settings/permissions.html
{% extends 'base.html' %}



{% block styletags %}
<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script
src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
{% endblock styletags %}



{% block content %}
<div class="content container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Settings</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="settings.html">Settings</a></li>
                    <li class="breadcrumb-item active">General Settings</li>
                </ul>
            </div>
        </div>
    </div>

    {% include '../utils/settings-menu.html' %}

    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table">
                <div class="card-body">
    
                    
    
                    <div class="mt-5 ml-5">  
                        <h2>Teacher Marks Upload Settings</h2>
                        <p>Toggle the switch below to enable or disable the ability for teachers to upload marks:</p>
                        <div class="switch">
                          <label>
                          <input type="checkbox" data-toggle="toggle" checked data-size="sm" id="toggleUploadSwitch">
                          <span class="lever"></span>
                          </label>
                          </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
   

</div>


{% endblock content %}



{% block scripttags %}
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<script>
    let btn = document.getElementById("toggleUploadSwitch")
    console.log(btn)
    $(document).ready(function() {
        $('#toggleUploadSwitch').change(function() {
            console.log("the button is active")
            let newStatus = $(this).is(':checked') ? 1 : 0;
            let url = "{% url 'settings:toggle-marks-uploads' %}"
            $.ajax({
                url: url,
                type: 'POST',
                data: {
                    'status': newStatus,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.status == 1) {
                        alert('Marks upload has been enabled for teachers.');
                    } else {
                        alert('Marks upload has been disabled for teachers.');
                    }
                },
                error: function() {
                    alert('An error occurred while updating the settings.');
                }
            });
        });
    });
</script>
{% endblock scripttags %}

src/templates/settings/session-settings.html
{% extends 'base.html' %}



{% block styletags %}

{% endblock styletags %}



{% block content %}
<div class="content container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Settings</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="settings.html">Settings</a></li>
                    <li class="breadcrumb-item active">General Settings</li>
                </ul>
            </div>
        </div>
    </div>

    {% include '../utils/settings-menu.html' %}

    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table">
                <div class="card-body">
    
                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title badge bg-warning text-wrap text-white">Current Session is: {{current_session}}</h3>
                            </div>
                            <div class="col-auto text-end float-end ms-auto download-grp">
                                <!-- <a href="#" class="btn btn-outline-primary me-2"><i class="fas fa-download"></i>
                                    Download</a> -->
                                <a class="btn btn-primary" href="#" data-bs-toggle="modal" data-bs-target="#add_subject">
                                    <i class="fas fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
    
                    <div class="table-responsive">
                        <table class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                            <thead class="student-thread">
                                <tr>
                                    
                                    <th>#</th>
                                    <th>Academic Session Name</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
    
                                {% for session in sessions %}
    
    
                                <tr>
                                    
                                    <td>{{forloop.counter}}</td>
                                    <td>{{session.name}}</td>
                                    <td>{{session.start_date}}</td>
                                    <td>{{session.end_date}}</td>
                                    <td> 
                                    {% if session.is_current %}
                                    <span class="badge bg-success">Active Session</span></td>
                                    {% else %}
                                    <span class="badge bg-warning">In Active</span></td>
                                    {% endif %}
                                        
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary">Action</button>
                                            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
                                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item btn btn-success text-white text-center" href="{% url 'sessions:session-mark-active' pkid=session.pkid %}">Mark Active</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item btn btn-warning text-white text-center" href="#" data-bs-toggle="modal"
                                                data-bs-target="#edit_session_{{session.pkid}}">Edit</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                        
    
                                <div class="modal custom-modal fade" id="edit_session_{{session.pkid}}" role="dialog">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <div class="form-header">
                                                    <h3>Edit Academic Session</h3>
                                                </div>
                                                <div class="card">
                                                    <div class="card-body">
                                                        <form action="{% url 'sessions:session-edit' session.pkid%}"
                                                            method="post">
                                                            {% csrf_token %}
                                                            <div class="row">
                                                                <div class="col-12">
                                                                    <h5 class="form-title"><span>Academic Session Information</span>
                                                                    </h5>
                                                                </div>
                                                                <div class="col-12">
                                                                    <div class="form-group local-forms">
                                                                        <label>Academic Session Name <span
                                                                                class="login-danger">*</span></label>
                                                                        <input value="{{session.name}}" name="academic_session_name"
                                                                            type="text" class="form-control" required>
                                                                    </div>
                                                                </div>
                                                                <div class="col-12">
                                                                    <div class="form-group local-forms">
                                                                        <label>Start Date </label>
                                                                        <input value="\" name="academic_session_start_date"
                                                                        type="date" class="form-control" >
                                                                    </div>
                                                                    <p class="badge bg-warning p-4 text-40">Current start date: {{session.start_date|date}}</p>
                                                                </div>
                                                               
                                                                <div class="col-12 row">
                                                                    <div class="student-submit col-6">
                                                                        <button type="submit"
                                                                            class="btn btn-primary">Submit</button>
                                                                    </div>
                                                                    <div class="student-submit col-6 ml-5">
                                                                        <a href="" data-bs-dismiss="modal"
                                                                            class="btn btn-danger">Cancel</a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
   

</div>

<div class="modal custom-modal fade" id="add_subject" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header">
                    <h3>Add Academic Session</h3>
                    <p style="font-size: 17px;" class="badge bg-warning text-wrap text-white">Enter the name of the session and leave the rest empty if you want the session to start today.</p>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'sessions:session-create' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="form-title"><span>Academic Session Information</span></h5>
                                </div>
                                <div class="col-12">
                                    <div class="form-group local-forms">
                                        <label>Academic Session Name <span class="login-danger">*</span></label>
                                        <input name="academic_session_name" type="text" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group local-forms">
                                        <label>Start Date</label>
                                        <input name="academic_session_start_date" type="date" class="form-control">
                                    </div>
                                </div>
                               
                                <div class="col-12 row">
                                    <div class="student-submit col-6">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                    <div class="student-submit col-6 ml-5">
                                        <a href="" data-bs-dismiss="modal" class="btn btn-danger">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripttags %}

{% endblock scripttags %}