src/apps/staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path("", views.admin_dashboard, name="admin-dashboard"),
    # Subjects.
    path("subjects/", views.list_all_subjects, name="subjects"),
    path("subjects/delete/<int:pkid>/", views.delete_subject, name="subjects-delete"),
    path("add-subjects", views.add_subject_view, name="subject-add"),
    path("edit-subjects/<int:pkid>/", views.edit_subject_view, name="subject-edit"),
    path(
        "assign-subjects/<int:pkid>/",
        views.assign_subject_to_classes,
        name="subjects-assign",
    ),
    path("create-admin", views.create_staff, name="create-admin"),
    path("list", views.list_admin, name="list-admin"),
    path("admin-marks", views.mark_list_admin_view, name="admin-marks"),
    path(
        "subject-marks-list/<int:class_pkid>/",
        views.subject_marks_list,
        name="subject-marks-list",
    ),
    path(
        "staff-upload-marks-file/<int:subject_pkid>/<int:class_pkid>/",
        views.staff_upload_marks,
        name="staff-upload-marks-file",
    ),
    path(
        "download-sample-subjects-file",
        views.download_sample_subject_file,
        name="download-sample-subjects-file",
    ),
    path(
        "upload-subjects-from-file",
        views.upload_subjects_from_file,
        name="upload-subjects-from-file",
    ),
]

src/apps/students/urls.py
from django.urls import path

from . import views

app_name = "students"


urlpatterns = [
    path("", views.list_student_view, name="student-list"),
    path(
        "<int:pkid>/<str:matricule>/", views.student_detail_view, name="student-detail"
    ),
    path(
        "edit/<int:pkid>/<str:matricule>/",
        views.edit_student_profile,
        name="student-edit",
    ),
    # path("delete/<int:pkid>/<str:matricule>/", views.delete, name="student-edit"),
    path(
        "student-record/<int:pkid>/<str:matricule>/",
        views.list_student_record,
        name="student-academic-record",
    ),
    path("add/", views.add_student_view, name="student-add"),
    path(
        "assign-optional-subjects/<int:student_pkid>/<str:student_matricule>/",
        views.add_optional_subjects_to_student,
        name="assign-optional-subjects",
    ),
    path(
        "download-class-list/",
        views.download_class_list,
        name="download-class-list",
    ),
    path(
        "upload-students/",
        views.upload_students_from_file,
        name="upload-students-from-file",
    ),
    path(
        "download-sample-file",
        views.download_sample_student_file,
        name="download-sample-file",
    ),
    # Marks
    path(
        "download-marks-sheet/<int:subject_pkid>/<int:class_pkid>",
        views.download_marksheet,
        name="mark-sheet-download",
    ),
    path(
        "upload-marks/<int:subject_pkid>/<int:class_pkid>",
        views.upload_marks1,
        name="marks-upload",
    ),
    path("marks", views.marks, name="marks"),
    path("verify-pin/", views.verify_student_pin, name="verify_pin"),
    path("student-dashboard", views.student_dashboard, name="student-dashboard"),
    path(
        "edit-mark/<int:mark_pkid>/<int:student_pkid>/",
        views.edit_student_marks,
        name="edit-mark",
    ),
    path(
        "fill-marks/<int:subject_pkid>/<int:class_pkid>/",
        views.fill_student_marks,
        name="fill-marks",
    ),
    path("update-fill-mark", views.update_fill_marks, name="update-fill-mark"),
    path(
        "teacher-modify-student-record/<int:subject_pkid>/<int:student_pkid>/<int:f_session>/<int:l_session>/",
        views.teacher_modify_student_mark,
        name="teacher-modify-student-record",
    ),
]

src/sms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import include, path

from apps.scelery.views import form_view
from apps.teachers import views
from apps.students.views import get_classes_by_department

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # local apps
    path("", include("apps.staff.urls", namespace="staff")),
    path("students/", include("apps.students.urls", namespace="students")),
    path("teachers/", include("apps.teachers.urls", namespace="teachers")),
    path("payments/", include("apps.fees.urls", namespace="fees")),
    path("settings/", include("apps.settings.urls", namespace="settings")),
    path("sessions/", include("apps.terms.urls", namespace="sessions")),
    path("reports/", include("apps.reports.urls", namespace="reports")),
    # Classes
    path("classes/", views.class_list_view, name="class-list"),
    path("add-class/", views.class_add_view, name="class-add"),
    path("edit/<int:pkid>/", views.class_edit_view, name="class-edit"),
    path("delete/<int:pkid>/", views.class_delete_view, name="class-delete"),
    path(
        "download-sample-class-upload/",
        views.download_sample_class_file,
        name="download-sample-class-upload",
    ),
    path(
        "upload-class-from-file",
        views.upload_classes_from_file,
        name="upload-class-from-file",
    ),
    # auth
    path("accounts/", include("apps.users.urls", namespace="users")),
    path(
        "password-reset-complete",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("attendance/", include("apps.attendance.urls", namespace="attendance")),
    path("leave/", include("apps.leave.urls", namespace="leave")),
    # testing
    path("form/", form_view, name="form"),
    path(
        "get-classes/",
        get_classes_by_department,
        name="get_classes_by_department",
    ),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/students/forms.py
from django import forms


class VerifyPinForm(forms.Form):
    email = forms.EmailField(
        label="Password",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Email"}
        ),
    )
    pin = forms.CharField(
        label="Password",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "PIN"}),
    )

src/apps/students/views.py
import csv
import json
import random
from datetime import datetime, time, timezone

import openpyxl
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from openpyxl import load_workbook, workbook
from openpyxl.utils import get_column_letter

from apps.attendance.models import Attendance
from apps.fees.models import Fee
from apps.profiles.models import ParentProfile
from apps.settings.models import Setting
from apps.terms.models import AcademicYear, ExaminationSession, Term
import logging

from .forms import VerifyPinForm
from .models import (
    Class,
    Mark,
    StudentProfile,
    StudentTempCreateProfile,
    Subject,
    Department,
    TeacherProfile,
    TeacherTempCreateProfile,
)


# Configure logging
logger = logging.getLogger(__name__)
from .utils import (
    check_student_is_owing,
    check_student_is_repeater,
    create_student_parent,
    create_student_pin,
    format_date,
    generate_random_pin,
    get_student_temp_account,
    get_teacher_temp_account,
    send_account_creation_email,
    send_password_reset_email,
)

User = get_user_model()

from faker import Faker

faker = Faker()
logger = logging.getLogger(__name__)


@login_required
def list_student_view(request):

    queryset = StudentProfile.objects.all()
    classes = Class.objects.all()
    departments = Department.objects.all()
    template_name = "students/list.html"
    context = {
        "section": "student-area",
        "deparments": departments,
        "students": queryset,
        "classes": classes,
    }

    return render(request, template_name, context)


@login_required
def student_detail_view(request, matricule, pkid):
    fee = None
    payment_history = None
    student = get_object_or_404(StudentProfile, matricule=matricule, pkid=pkid)
    extra_payment_history = student.extra_payments.all()
    # get the current academic year
    current_year = AcademicYear.objects.get(is_current=True)
    terms = Term.objects.filter(academic_year=current_year)

    # Get the payment history for the current year
    fees = Fee.objects.filter(student=student, academic_year=current_year)
    payment_history = []
    total_amount_paid = 0
    for fee in fees:
        payment_his = fee.fee_history.all()
        for payment in payment_his:
            payment_history.append(payment)
            total_amount_paid += payment.amount_paid
    # Grab all the mark records associated to this student
    marks = student.student_marks.all()

    # Get all the subjects in the class the student belongs to
    # and those optionally added by the student
    subjects1 = student.current_class.subjects.all()
    # get optoinal subjects for the particular student
    optional_subjects = student.optional_subjects.all()

    distinct_subjects = set(list(subjects1) + list(optional_subjects))

    pin = StudentTempCreateProfile.objects.filter(student=student)
    if pin.exists():
        pin = pin.first()
    else:
        pin = None

    template_name = "students/details.html"
    context = {
        "section": "student-area",
        "student_detial_section": True,
        "student": student,
        "payment_history": payment_history,
        "number_of_payments": len(payment_history),
        "marks": marks,
        "total_payment": total_amount_paid,
        "subjects": distinct_subjects,
        "pin": pin,
        "extra_payments": extra_payment_history,
        "terms": terms,
    }

    return render(request, template_name, context)


@login_required
def add_student_view(request):
    classes = Class.objects.all()
    if request.method == "POST":
        print(request.POST)

        pin = request.POST.get("password_reset_pin")
        parent_fname = request.POST.get("first_name")
        parent_occupation = request.POST.get("parent-occupation")
        parent_phone = request.POST.get("parent-phone")
        parent_email = request.POST.get("parent-email")
        parent_address = request.POST.get("parent-address")
        parent_role = request.POST.get("parent-role")
        st_class = request.POST.get("class")

        # Check if student pin is valid
        # should not be greater or less than 4 in length
        if len(pin) == 4:
            # create temp
            pass
        else:
            messages.error(
                "Password reset pin has incorrect length, should be exactly 4."
            )
            return redirect(reverse("students:student-add"))

        # Get class in which student is part of
        print("for the class", st_class)
        student_class = get_object_or_404(Class, pkid=int(st_class))

        # Create parent for student
        student_parent, created = ParentProfile.objects.get_or_create(
            first_name=parent_fname,
            phone=parent_phone,
            occupation=parent_occupation,
            address=parent_address,
            email=parent_email,
            role=parent_role,
        )

        student_parent.save()

        st_fname = request.POST.get("first_name")
        st_lname = request.POST.get("last_name")
        st_gender = request.POST.get("selected_gender")
        st_email = request.POST.get("email")
        st_dob = request.POST.get("dob")
        st_address = request.POST.get("address")
        st_phone = request.POST.get("phone")
        st_domain = request.POST.get("domain")
        st_image = request.FILES.get("profile_photo")
        matricule = request.POST.get("matricule")

        # Create the user instance
        # construct a valid date out of the html date
        date_string_from_form = st_dob

        dob = datetime.strptime(date_string_from_form, "%Y-%m-%d").date()
        # Create a specific time
        specific_time = time(8, 51, 2)

        dob_with_time = datetime.combine(dob, specific_time, tzinfo=timezone.utc)

        # Construct faker usernames, this is done assuming that the usernames are not important to the students
        # we avoid using direct fake usernames, so as to avoid unique constrainst failure in the database
        # This is why the random digit is added to the end of every fake username generated by faker
        # faker_username = st_fname
        # attache random digit to the end
        # faker_username + str(random.randint(0, 9))

        if not st_email:
            st_email = faker.email()

        user, created = User.objects.get_or_create(
            username=st_fname,
            first_name=st_fname,
            last_name=st_lname,
            email=st_email,
            is_student=True,
            dob=dob_with_time,
        )
        if created:
            user.save()

        # Create student instance

        student, created = StudentProfile.objects.get_or_create(
            matricule=matricule,
            user=user,
            parent=student_parent,
            current_class=student_class,
            gender=st_gender,
            phone_number=st_phone,
            # profile_photo=st_photo,
            address=st_address,
            domain=st_domain,
        )

        if created:

            student.save()
            if st_image:
                student.profile_photo = st_image
            student.save()
            create_student_pin(student, pin)
            send_account_creation_email(request, student.user)
            return redirect(reverse("students:student-list"))
        else:
            messages.error(request, "Student already exist.")
            return redirect(reverse("students:student-list"))
    departments = Department.objects.all()
    template_name = "students/add.html"

    context = {
        "section": "student-area",
        "classes": classes,
        "departments": departments,
    }

    return render(request, template_name, context)


def get_classes_by_department(request):
    department_id = request.GET.get("department_id")
    classes = Class.objects.filter(department_id=department_id).values(
        "pkid", "class_name"
    )
    return JsonResponse(list(classes), safe=False)


@login_required
def edit_student_profile(request, pkid, matricule):
    student = get_object_or_404(StudentProfile, pkid=pkid, matricule=matricule)

    if request.method == "POST":
        st_class = request.POST.get("student_class")
        print("for the class", st_class)
        student_class = get_object_or_404(Class, pkid=int(st_class))

        st_fname = request.POST.get("first_name")
        st_lname = request.POST.get("last_name")
        st_gender = request.POST.get("selected_gender")
        st_email = request.POST.get("email")
        st_dob = request.POST.get("dob")
        st_address = request.POST.get("address")
        st_phone = request.POST.get("phone")
        st_domain = request.POST.get("domain")
        st_image = request.FILES.get("profile_photo")
        st_matricule = request.POST.get("matricule")

        # Parse date string from form
        dob = datetime.strptime(st_dob, "%Y-%m-%d").date()
        specific_time = time(8, 51, 2)

        dob_with_time = datetime.combine(dob, specific_time, tzinfo=timezone.utc)
        # <class 'datetime.datetime'>
        # Update user fields
        student.user.first_name = st_fname
        student.user.last_name = st_lname
        student.user.email = st_email
        student.user.dob = dob_with_time

        if st_image:
            student.profile_photo = st_image
        student.user.save()

        # Update student fields
        student.current_class = student_class
        student.gender = st_gender
        student.phone_number = st_phone
        student.address = st_address
        student.domain = st_domain

        if request.user.is_admin:
            student.matricule = st_matricule
        else:
            messages.warning(

src/templates/students/fill-marks.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h3>Session: {{ session }}</h3>
    <h3>Subject: {{ subject }}</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Mark</th>
                <th>Sesssion</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.user.get_fullname }}</td>
                    <td>
                        <input type="number" class="mark-input" data-student-id="{{ student.pkid }}" data-subject="{{ subject.pkid }}" data-session="{{session.pkid}}" value="{{ student.mark }}">
                    </td>
                    <td>{{ session }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <button id="save-marks-btn" class="btn btn-primary">Save All Marks</button>
{% endblock content %}

{% block scripttags %}
<script src="{% static 'assets/plugins/dragula/js/dragula.min.js' %}"></script>
<script src="{% static 'assets/plugins/dragula/js/drag-drop.min.js' %}"></script>

<script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'assets/plugins/scrollbar/scrollbar.min.js' %}"></script>
<script src="{% static 'assets/plugins/scrollbar/custom-scroll.js' %}"></script>


<script src="{% static 'assets/plugins/alertify/alertify.min.js' %}"></script>
<script src="{% static 'assets/plugins/alertify/custom-alertify.min.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const markInputs = document.querySelectorAll('.mark-input');

        markInputs.forEach(input => {
            input.addEventListener('change', function () {
                const studentId = this.dataset.studentId;
                const subject = this.dataset.subject;
                const mark = this.value;
                const session_pkid = this.dataset.session

                fetch('{% url "students:update-fill-mark" %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        student_id: studentId,
                        subject: subject,
                        mark: mark,
                        session: session_pkid
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        // alert('Mark updated successfully');
                        alertify.success("Subjects updated successfully")
                    } else {
                        alert('Error updating mark');
                    }
                });
            });
        });
    });
</script>
{% endblock scripttags %}

src/templates/students/list.html
{% extends 'base.html' %}
{% load static %}
{% load student_tags %}


{% block stylelinks %}
<link rel="stylesheet" href="{% static 'assets/plugins/datatables/datatables.min.css' %}">
{% endblock stylelinks %}



{% block content %}
<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">Students</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="students.html">Student</a></li>
                        <li class="breadcrumb-item active">All Students</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% comment %} <div class="student-group-form">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search by ID ...">
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search by Name ...">
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search by Phone ...">
                </div>
            </div>
            <div class="col-lg-2">
                <div class="search-student-btn">
                    <button type="btn" class="btn btn-primary">Search</button>
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table comman-shadow">
                <div class="card-body">

                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">List of Registered Students</h3>
                            </div>
                            <div class="col-auto text-end float-end ms-auto download-grp">
                                <!-- <a href="students.html" class="btn btn-outline-gray me-2 active"><i
                                        class="feather-list"></i></a>
                                <a href="students-grid.html" class="btn btn-outline-gray me-2"><i
                                        class="feather-grid"></i></a> -->
                                    <a href="#" class="btn btn-outline-primary me-2" data-bs-toggle="modal" data-bs-target="#download_class_list"><i
                                        class="fas fa-download"></i> Download</a>
                                    <a href="{% url 'students:upload-students-from-file' %}" class="btn btn-outline-primary me-2"><i
                                        class="fas fa-upload"></i> Upload File</a>
                                <a href="{% url 'students:student-add' %}" class="btn btn-primary"><i
                                        class="fas fa-plus"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table
                            class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                            <thead class="student-thread">
                                <tr>
                                    <th>#</th>
                                    <th>Matricule</th>
                                    <th>Name</th>
                                    <th>Class</th>
                                    <th>DOB</th>
                                    <th>Parent Name</th>
                                    <th>Mobile Number</th>
                                    <th>Address</th>
                                    <th>Fee Status</th>
                                    <th class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for student in students %}                                    
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td><a  style="color: blue" href="{% url 'students:student-detail' pkid=student.pkid matricule=student.matricule%}">{{student.matricule}}</a></td>
                                        

                                        {% if student.profile_photo %}
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="{% url 'students:student-detail' pkid=student.pkid matricule=student.matricule%}"
                                                        class="avatar avatar-sm me-2">
                                                        <img class="avatar-img rounded-circle"
                                                            src="{{ student.profile_photo.url|check_image_exists }}"
                                                            alt="User Image">
                                                    </a>
                                                    <a href="{% url 'students:student-detail' pkid=student.pkid matricule=student.matricule%}">{{student.user.get_fullname}}</a>
                                                </h2>
                                            </td>
                                        {% else %}
                                            <h2>something else</h2>
                                        {% endif %}
                                        <td>{{student.current_class.class_name}}</td>
                                        <td>{{ student.user.dob|date:"j M Y" }}</td>
                                        <td>{{ student.parent.full_name }}</td>
                                        <td>{{ student.phone_number }}</td>
                                        <td>{{ student.address }}</td>
                                        <td>
            
                                            {% if student.is_owing %}
                                                <span class="badge badge-warning">Is Owing</span>
                                            {% else %}
                                                <span class="badge badge-success">Completed</span>
                                            {% endif %}                                                
                                        </td>
                                        <td class="text-right">
                                            <div class="actions">
                                                <a href="{% url 'students:student-detail' pkid=student.pkid matricule=student.matricule%}" class="btn btn-sm bg-success-light me-2">
                                                    <i class="feather-eye"></i>
                                                </a>
                                                <a href="{% url 'students:student-edit' pkid=student.pkid matricule=student.matricule %}" class="btn btn-sm bg-success-light mr-2">
                                                    <i class="fas fa-pen"></i>
                                                </a>
                                                <a href="" class="btn btn-sm bg-danger-light">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% comment %} download class list modal {% endcomment %}

<div class="modal custom-modal fade" id="download_class_list" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header">
                    <h3>Download Class List</h3>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'students:download-class-list' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="form-title"><span>Subject Information</span></h5>
                                </div>
                                
                                <div class="col-12">
                                    <div class="form-group local-forms">
                                        <label>Class <span class="login-danger">*</span></label>
                                        <select class="form-control" name="selected_class_id">
                                            <option value="all">
                                                All</option>
                                            {% for class in classes %}
                                            <option value="{{class.pkid}}">
                                                {{class.grade_level}} - {{class.class_name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12 row">
                                    <div class="student-submit col-6">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                    <div class="student-submit col-6 ml-5">
                                        <a href="" data-bs-dismiss="modal" class="btn btn-danger">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


<li><a href="">Student Edit</a></li>

{% block scripttags %}
<script src="{% static 'assets/plugins/datatables/datatables.min.js' %}"></script>
{% endblock scripttags %}
    