src/apps/leave/urls.py
from django.urls import path

from . import views

app_name = "leave"

urlpatterns = [
    path("", views.list_leave, name="list-leave"),
    path("add-leave", views.add_leave, name="add-leave"),
    path(
        "approve-leave/<int:leave_pkid>/<str:leave_type>",
        views.approve_leave,
        name="approve-leave",
    ),
    path(
        "reject-leave/<int:leave_pkid>/<str:leave_type>",
        views.reject_leave,
        name="reject-leave",
    ),
    path("see-leave/<int:pkid>/", views.see_leave, name="see-leave"),
    path("list-per-person", views.get_user_leaves, name="leave-per-person"),
]

src/apps/reports/urls.py
from django.urls import path

from . import controller, views

app_name = "reports"


urlpatterns = [
    path("", views.reports, name="reports"),
    path(
        "generate-report-card",
        controller.create_report_cards,
        name="generate_report_cards",
    ),
    path(
        "generate-report/<int:student_pkid>/",
        controller.create_one_report_card,
        name="generate_single_report_card",
    ),
    path(
        "generate-class-master-report",
        views.create_class_master_report,
        name="genereate_class_master_report",
    ),
    path(
        "download-class-master-report/<int:class_pkid>",
        views.download_class_master_report,
        name="download_class_master_report",
    ),
    path("view-reports/", controller.view_reports, name="view-reports"),
    path(
        "download-report/<str:file_name>/",
        controller.download_report,
        name="download-report",
    ),
]

src/apps/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"


urlpatterns = [
    path("", views.settings_view, name="settings-home"),
    path("sessions/", views.session_settings_view, name="setting-sessions"),
    path("terms/", views.term_settings_view, name="setting-terms"),
    path("exam-sessions/", views.exam_session_view, name="setting-exam-sessions"),
    path("update-settings/", views.update_settings, name="settings-update"),
    path("fee-settings/", views.fee_settings, name="settings-fees"),
    path(
        "toggle-marks-uploads/",
        views.toggle_teacher_can_upload_marks_permission,
        name="toggle-marks-uploads",
    ),
]

src/apps/staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path("", views.admin_dashboard, name="admin-dashboard"),
    # Subjects.
    path("subjects/", views.list_all_subjects, name="subjects"),
    path("subjects/delete/<int:pkid>/", views.delete_subject, name="subjects-delete"),
    path("add-subjects", views.add_subject_view, name="subject-add"),
    path("edit-subjects/<int:pkid>/", views.edit_subject_view, name="subject-edit"),
    path(
        "assign-subjects/<int:pkid>/",
        views.assign_subject_to_classes,
        name="subjects-assign",
    ),
    path("create-admin", views.create_staff, name="create-admin"),
    path("list", views.list_admin, name="list-admin"),
    path("admin-marks", views.mark_list_admin_view, name="admin-marks"),
    path(
        "subject-marks-list/<int:class_pkid>/",
        views.subject_marks_list,
        name="subject-marks-list",
    ),
    path(
        "staff-upload-marks-file/<int:subject_pkid>/<int:class_pkid>/",
        views.staff_upload_marks,
        name="staff-upload-marks-file",
    ),
    path(
        "download-sample-subjects-file",
        views.download_sample_subject_file,
        name="download-sample-subjects-file",
    ),
    path(
        "upload-subjects-from-file",
        views.upload_subjects_from_file,
        name="upload-subjects-from-file",
    ),
]

src/sms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import include, path

from apps.scelery.views import form_view
from apps.teachers import views
from apps.students.views import get_classes_by_department

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # local apps
    path("", include("apps.staff.urls", namespace="staff")),
    path("students/", include("apps.students.urls", namespace="students")),
    path("teachers/", include("apps.teachers.urls", namespace="teachers")),
    path("payments/", include("apps.fees.urls", namespace="fees")),
    path("settings/", include("apps.settings.urls", namespace="settings")),
    path("sessions/", include("apps.terms.urls", namespace="sessions")),
    path("reports/", include("apps.reports.urls", namespace="reports")),
    # Classes
    path("classes/", views.class_list_view, name="class-list"),
    path("add-class/", views.class_add_view, name="class-add"),
    path("edit/<int:pkid>/", views.class_edit_view, name="class-edit"),
    path("delete/<int:pkid>/", views.class_delete_view, name="class-delete"),
    path(
        "download-sample-class-upload/",
        views.download_sample_class_file,
        name="download-sample-class-upload",
    ),
    path(
        "upload-class-from-file",
        views.upload_classes_from_file,
        name="upload-class-from-file",
    ),
    # auth
    path("accounts/", include("apps.users.urls", namespace="users")),
    path(
        "password-reset-complete",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("attendance/", include("apps.attendance.urls", namespace="attendance")),
    path("leave/", include("apps.leave.urls", namespace="leave")),
    # testing
    path("form/", form_view, name="form"),
    path(
        "get-classes/",
        get_classes_by_department,
        name="get_classes_by_department",
    ),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/utils/sidebars/admin-sidebar.html
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>

                <li class="{% if request.path == '/'  %}active{% endif %}">
                    <a href="{% url 'staff:admin-dashboard' %}"><i class="feather-grid"></i> <span>Home</span></a>
                </li>

                <li class="submenu {% if section == 'student-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-graduation-cap"></i> <span> Students</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:student-list' %}" class="{% if request.path == '/students/'  %}active{% endif %}">Student List</a></li>
                        <!-- <li><a href="student-details.html">Student View</a></li> -->
                        <li><a href="{% url 'students:student-add' %}" class="{% if request.resolver_match.url_name == 'student-add'  %}active{% endif %}">Student Add</a></li>
                        
                        {% if student_detial_section %}
                            <li><a href="" class="active">Student View</a></li>
                        {% endif %}
                            
                    </ul>
                </li>
                <li class="submenu {% if section == 'teachers-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Teachers</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'teachers:teachers-list' %}" class="{% if request.path == '/teachers/'  %}active{% endif %}">Teacher List</a></li>
                        <!-- <li><a href="teacher-details.html">Teacher View</a></li> -->
                        
                        <li><a href="{% url 'teachers:teachers-add' %}" class="{% if request.resolver_match.url_name == 'teachers-add'  %}active{% endif %}">Teacher Add</a></li>
                        <li><a href="{% url 'teachers:download-teacher-sample-file' %}" class="">Download Sample</a></li>
                        <!-- <li><a href="edit-teacher.html">Teacher Edit</a></li> -->
                    </ul>
                </li>
                <li class="submenu {% if section == 'class-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Classes</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <!-- <li><a href="{% url 'teachers:teachers-list' %}" class="{% if request.path == '/teachers/'  %}active{% endif %}">Teacher List</a></li> -->
                        <!-- <li><a href="teacher-details.html">Teacher View</a></li> -->
                        <li><a href="{% url 'class-list' %}" class="{% if request.resolver_match.url_name == 'class-list'  %}active{% endif %}">Classes</a></li>
                        <li><a href="{% url 'class-add' %}" class="{% if request.resolver_match.url_name == 'class-add'  %}active{% endif %}">Class Add</a></li>
                        <li><a href="{% url 'download-sample-class-upload' %}" class="">Download Sample</a></li>

                        <!-- <li><a href="edit-teacher.html">Teacher Edit</a></li> -->
                    </ul>
                </li>
                <li class="submenu {% if section == 'subjects-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        
                        <li><a href="{% url 'staff:subjects' %}" class="{% if section == 'subjects-area'  %}active{% endif %}">Subject List</a></li>
                        <li><a href="{% url 'staff:subject-add' %}" class="{% if section == 'add-subject'  %}active{% endif %}">Add Subject</a></li>
          
                        <li><a href="{% url 'staff:download-sample-subjects-file' %}">Download Sample</a></li>
                    </ul>
                </li>
                <li class="{% if section == 'settings'  %}active{% endif %}">
                    <a href="{% url 'settings:settings-home' %} " ><i class="fas fa-cog"></i> <span>Settings</span></a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'admin-marks'  %}active{% endif %}">
                    <a href="{% url 'staff:admin-marks' %} " ><i class="fas fa-chart-line"></i> <span>Marks</span></a>
                </li>

                <li class="{% if section == 'reports-area'  %}active{% endif %}">
                    <a href="{% url 'reports:reports' %}" ><i class="fas fa-book-reader"></i> <span>Reports</span></a>
                </li>


                <li class="submenu {% if section == 'attendance-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Attendance</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'attendance:attendance_class_list' %}">Manage Attendance</a></li>
                    </ul>
                </li>



                <!-- <li class="submenu">
                    <a href="#"><i class="fas fa-certificate"></i> <span> Marks</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:marks' %}">Marks</a></li>
                        <li><a href="add-department.html">Department Add</a></li>
                        <li><a href="edit-department.html">Department Edit</a></li>
                    </ul>
                </li> -->
               
                {% comment %} <li class="submenu">
                    <a href="#"><i class="fas fa-clipboard"></i> <span> Invoices</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="invoices.html">Invoices List</a></li>
                        <li><a href="invoice-grid.html">Invoices Grid</a></li>
                        <li><a href="add-invoice.html">Add Invoices</a></li>
                        <li><a href="edit-invoice.html">Edit Invoices</a></li>
                        <li><a href="view-invoice.html">Invoices Details</a></li>
                        <li><a href="invoices-settings.html">Invoices Settings</a></li>
                    </ul>
                </li> {% endcomment %}
                <li class="menu-title">
                    <span>Management</span>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-users"></i> <span> Accounts</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'staff:create-admin' %}" class="{% if request.resolver_match.url_name == 'create-admin'  %}active{% endif %}">Add User</a></li>
                        <li><a href="{% url 'staff:list-admin' %}" class="{% if request.resolver_match.url_name == 'list-admin'  %}active{% endif %}">List Admin</a></li>
                    </ul>
                </li>

                <li class="{% if request.resolver_match.url_name == 'admin-marks'  %}active{% endif %}">
                    <a href="{% url 'reports:view-reports' %} " ><i class="fas fa-chart-line"></i> <span>See reports</span></a>
                </li>
              
              
            </ul>
        </div>
    </div>
</div>

src/templates/utils/sidebars/student-sidebar.html
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>

                <li class="{% if section == 'student-dashboard' %}active{% endif %}">
                    <a href="{% url 'students:student-dashboard' %}"><i class="feather-grid"></i> <span>Home</span></a>
                  </li>
                  
                <li class="{% if section == 'student-dashboad' %}active{% endif %}">
                <a href="{% url 'students:student-detail' student.pkid student.matricule %}"><i class="fas fa-user"></i> <span>Profile</span></a>
                </li>
                

                <li class="{% if section == 'student-dashboad' %}active{% endif %}">
                    <a href="{% url 'students:student-detail' student.pkid student.matricule %}"><i class="fas fa-book"></i> <span>View Subjects</span></a>
                </li>
                
                
                <li class="{% if section == 'student-dashbard' %}active{% endif %}">
                    <a href="{% url 'students:student-academic-record' pkid=student.pkid matricule=student.matricule%}"><i class="fas fa-folder"></i> <span>View Academic Record</span></a>
                </li> 
              

            

                <!-- <li class="submenu">
                    <a href="#"><i class="fas fa-certificate"></i> <span> Marks</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:marks' %}">Marks</a></li>
                        <li><a href="add-department.html">Department Add</a></li>
                        <li><a href="edit-department.html">Department Edit</a></li>
                    </ul>
                </li> -->
               
                {% comment %} <li class="submenu">
                    <a href="#"><i class="fas fa-clipboard"></i> <span> Invoices</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="invoices.html">Invoices List</a></li>
                        <li><a href="invoice-grid.html">Invoices Grid</a></li>
                        <li><a href="add-invoice.html">Add Invoices</a></li>
                        <li><a href="edit-invoice.html">Edit Invoices</a></li>
                        <li><a href="view-invoice.html">Invoices Details</a></li>
                        <li><a href="invoices-settings.html">Invoices Settings</a></li>
                    </ul>
                </li> {% endcomment %}
              
              
              
            </ul>
        </div>
    </div>
</div>

src/templates/utils/sidebars/teachers-sidebar.html
<div class="sidebar" id="sidebar">
  <div class="sidebar-inner slimscroll">
    <div id="sidebar-menu" class="sidebar-menu">
      <ul>
        <li class="menu-title">
          <span>Main Menu</span>
        </li>

        <li class="{% if section == 'teacher-dashboard' %}active{% endif %}">
            <a href="{% url 'teachers:teacher-dashboard' %}"><i class="feather-grid"></i> <span>Home</span></a>
          </li>
    
        
        
        
        
        <li class="{% if request.resolver_match.url_name == 'marks' %}active{% endif %}">
          <a href="{% url 'students:marks' %} "><i class="fas fa-chart-line"></i> <span>Marks</span></a>
        </li>

{% comment %}         
        <li class="{% if section == 'reports-area' %}active{% endif %}">
            <a href="{% url 'reports:reports' %}"><i class="fas fa-book-reader"></i> <span>Generate Reports</span></a>
          </li>
   {% endcomment %}

        <li class="submenu {% if section == 'attendance-area' %}active{% endif %}">
          <a href="#"><i class="fas fa-user-check"></i> <span>Attendance</span> <span class="menu-arrow"></span></a>
          <ul>
            <li>
              <a href="{% url 'attendance:take-attendance' %} ">Take Attendance</a>
            </li>
            <li>
              <a href="{% url 'attendance:view-attendance' %}">View Attendance</a>
            </li>
          </ul>
        </li>

        <li class="submenu {% if section == 'leave-per-person' %}active{% endif %}">
            <a href="#"><i class="fas fa-calendar-check"></i> <span>Leave</span> <span class="menu-arrow"></span></a>
            <ul>
              <li>
                <a href="{% url 'leave:add-leave' %} ">Apply</a>
              </li>
              <li>
                <a href="{% url 'leave:leave-per-person' %}">List</a>
              </li>
            </ul>
          </li>
  

        <!--  <li class="submenu">
                    <a href="#"><i class="fas fa-certificate"></i> <span> Marks</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:marks' %}">Marks</a></li>
                        <li><a href="add-department.html">Department Add</a></li>
                        <li><a href="edit-department.html">Department Edit</a></li>
                    </ul>
                </li>  -->

        {% comment %} <li class="submenu">
          <a href="#"><i class="fas fa-clipboard"></i> <span>Invoices</span> <span class="menu-arrow"></span></a>
          <ul>
            <li>
              <a href="invoices.html">Invoices List</a>
            </li>
            <li>
              <a href="invoice-grid.html">Invoices Grid</a>
            </li>
            <li>
              <a href="add-invoice.html">Add Invoices</a>
            </li>
            <li>
              <a href="edit-invoice.html">Edit Invoices</a>
            </li>
            <li>
              <a href="view-invoice.html">Invoices Details</a>
            </li>
            <li>
              <a href="invoices-settings.html">Invoices Settings</a>
            </li>
          </ul>
        </li> {% endcomment %}
      
      </ul>
    </div>
  </div>
</div>