src/apps/reports/urls.py
from django.urls import path

from . import controller, views

app_name = "reports"


urlpatterns = [
    path("", views.reports, name="reports"),
    path(
        "generate-report-card",
        controller.create_report_cards,
        name="generate_report_cards",
    ),
    path(
        "generate-report/<int:student_pkid>/",
        controller.create_one_report_card,
        name="generate_single_report_card",
    ),
    path(
        "generate-class-master-report",
        views.create_class_master_report,
        name="genereate_class_master_report",
    ),
    path(
        "download-class-master-report/<int:class_pkid>",
        views.download_class_master_report,
        name="download_class_master_report",
    ),
    path("view-reports/", controller.view_reports, name="view-reports"),
    path(
        "download-report/<str:file_name>/",
        controller.download_report,
        name="download-report",
    ),
]

src/apps/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"


urlpatterns = [
    path("", views.settings_view, name="settings-home"),
    path("sessions/", views.session_settings_view, name="setting-sessions"),
    path("terms/", views.term_settings_view, name="setting-terms"),
    path("exam-sessions/", views.exam_session_view, name="setting-exam-sessions"),
    path("update-settings/", views.update_settings, name="settings-update"),
    path("fee-settings/", views.fee_settings, name="settings-fees"),
    path(
        "toggle-marks-uploads/",
        views.toggle_teacher_can_upload_marks_permission,
        name="toggle-marks-uploads",
    ),
]

src/apps/staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path("", views.admin_dashboard, name="admin-dashboard"),
    # Subjects.
    path("subjects/", views.list_all_subjects, name="subjects"),
    path("subjects/delete/<int:pkid>/", views.delete_subject, name="subjects-delete"),
    path("add-subjects", views.add_subject_view, name="subject-add"),
    path("edit-subjects/<int:pkid>/", views.edit_subject_view, name="subject-edit"),
    path(
        "assign-subjects/<int:pkid>/",
        views.assign_subject_to_classes,
        name="subjects-assign",
    ),
    path("create-admin", views.create_staff, name="create-admin"),
    path("list", views.list_admin, name="list-admin"),
    path("admin-marks", views.mark_list_admin_view, name="admin-marks"),
    path(
        "subject-marks-list/<int:class_pkid>/",
        views.subject_marks_list,
        name="subject-marks-list",
    ),
    path(
        "staff-upload-marks-file/<int:subject_pkid>/<int:class_pkid>/",
        views.staff_upload_marks,
        name="staff-upload-marks-file",
    ),
    path(
        "download-sample-subjects-file",
        views.download_sample_subject_file,
        name="download-sample-subjects-file",
    ),
    path(
        "upload-subjects-from-file",
        views.upload_subjects_from_file,
        name="upload-subjects-from-file",
    ),
]

src/apps/users/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

# Class-based password reset views
# - PasswordResetView sends the mail
# - PasswordResetDoneView shows a success message for the above
# - PasswordResetConfirmView checks the link the user clicked and
#   prompts for a new password
# - PasswordResetCompleteView shows a success message for the above


app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="user-login"),
    path("logout/", views.logout_view, name="user-logout"),
    path(
        "reset-password",
        PasswordResetView.as_view(success_url="password-reset-done"),
        name="reset_password",
    ),
    path(
        "password-reset-done",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

src/sms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import include, path

from apps.scelery.views import form_view
from apps.teachers import views
from apps.students.views import get_classes_by_department

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # local apps
    path("", include("apps.staff.urls", namespace="staff")),
    path("students/", include("apps.students.urls", namespace="students")),
    path("teachers/", include("apps.teachers.urls", namespace="teachers")),
    path("payments/", include("apps.fees.urls", namespace="fees")),
    path("settings/", include("apps.settings.urls", namespace="settings")),
    path("sessions/", include("apps.terms.urls", namespace="sessions")),
    path("reports/", include("apps.reports.urls", namespace="reports")),
    # Classes
    path("classes/", views.class_list_view, name="class-list"),
    path("add-class/", views.class_add_view, name="class-add"),
    path("edit/<int:pkid>/", views.class_edit_view, name="class-edit"),
    path("delete/<int:pkid>/", views.class_delete_view, name="class-delete"),
    path(
        "download-sample-class-upload/",
        views.download_sample_class_file,
        name="download-sample-class-upload",
    ),
    path(
        "upload-class-from-file",
        views.upload_classes_from_file,
        name="upload-class-from-file",
    ),
    # auth
    path("accounts/", include("apps.users.urls", namespace="users")),
    path(
        "password-reset-complete",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("attendance/", include("apps.attendance.urls", namespace="attendance")),
    path("leave/", include("apps.leave.urls", namespace="leave")),
    # testing
    path("form/", form_view, name="form"),
    path(
        "get-classes/",
        get_classes_by_department,
        name="get_classes_by_department",
    ),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/utils/footer.html
<footer>
    <p>Copyright © 2024 School.</p>
</footer>

src/templates/utils/header.html
{% load static %}
{% load session_tags %}



<div class="header">

    <div class="header-left">
        <a href="index.html" class="logo">
            <img src="{% static 'assets/img/logo.png' %}" alt="Logo">
        </a>
        <a href="index.html" class="logo logo-small">
            <img src="{% static 'assets/img/logo-small.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>
    <div class="menu-toggle">
        <a href="javascript:void(0);" id="toggle_btn">
            <i class="fas fa-bars"></i>
        </a>
    </div>

    {% comment %} <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form> 

    </div> {% endcomment %}
    <a class="mobile_btn" id="mobile_btn">
        <i class="fas fa-bars"></i>
    </a>

    <ul class="nav user-menu">
        <li><div class="d-none d-sm-block">
            <h3 style="margin-left: 20px; background-color: yellow;" class="page-title text-center">{% current_working_session %}</h3>
        </div> </li>
        <li class="nav-item dropdown noti-dropdown language-drop me-2">
            <a href="#" class="dropdown-toggle nav-link header-nav-list" data-bs-toggle="dropdown">
                <img src="{% static 'assets/img/icons/header-icon-01.svg' %}" alt="">
            </a>
            <div class="dropdown-menu ">
                <div class="noti-content">
                    <div>
                        <a class="dropdown-item" href="javascript:;"><i
                                class="flag flag-lr me-2"></i>English</a>
                        {% comment %} <a class="dropdown-item" href="javascript:;"><i
                                class="flag flag-bl me-2"></i>Francais</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </li> 
        
        {% comment %} <li class="nav-item dropdown noti-dropdown me-2">
            
            <a href="#" class="dropdown-toggle nav-link header-nav-list" data-bs-toggle="dropdown">
                <img src="{% static 'assets/img/icons/header-icon-05.svg' %}" alt="">
            </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                        <li class="notification-message">
                            <a href="#">
                                <div class="media d-flex">
                                    <span class="avatar avatar-sm flex-shrink-0">
                                        <img class="avatar-img rounded-circle" alt="User Image"
                                            src="{% static 'assets/img/profiles/avatar-02.jpg' %}">
                                    </span>
                                    <div class="media-body flex-grow-1">
                                        <p class="noti-details"><span class="noti-title">School System</span> has
                                            approved <span class="noti-title">your estimate</span></p>
                                        <p class="noti-time"><span class="notification-time">4 mins ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        
                     
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="#">View all Notifications</a>
                </div>
            </div>
        </li> {% endcomment %}


        <li class="nav-item zoom-screen me-2">
            <a href="#" class="nav-link header-nav-list win-maximize">
                <img src="{% static 'assets/img/icons/header-icon-04.svg' %}" alt="">
            </a>
        </li>

        <li class="nav-item dropdown has-arrow new-user-menus">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                <span class="user-img">
                    <img class="rounded-circle" src="{{request.user.get_profile.profile_photo.url}}" width="31"
                        alt="profile picture">
                    <div class="user-text">
                        {% if user.is_authenticated %}
                            <h6>{{user.username | capfirst}}</h6>
                        {% else %}   
                            <h6>Unknown</h6>

                        {% endif %}
                        {% if user.is_staff %}
                            <p class="text-muted mb-0">Superman</p>
                        {% elif user.is_admin %}                           
                            <p class="text-muted mb-0">Administrator</p>
                        {% elif user.is_teacher %}
                            <p class="text-muted mb-0">Teacher</p>
                        {% elif user.is_student %}
                            <p class="text-muted mb-0">Student</p>
                        {% endif %}
                    </div>
                </span>
            </a>
            <div class="dropdown-menu">
                <div class="user-header">
                    <div class="avatar avatar-sm">
                        <img src="{% static 'assets/img/profiles/avatar-01.jpg' %}" alt="User Image"
                            class="avatar-img rounded-circle">
                    </div>
                    <div class="user-text">
                        
                        {% if user.is_authenticated %}
                            <h6>{{user.get_fullname}}</h6>
                        {% else %}   
                            <h6>Unknown</h6>

                        {% endif %}

                        
                        {% if is_student_profile %}
                            <p class="text-muted mb-0">Student</p>
                        {% elif is_admin_profile %}                           
                            <p class="text-muted mb-0">Administrator</p>
                        {% elif is_teacher_profile %}
                            <p class="text-muted mb-0">Teacher</p>
                        {% endif %}
                            


                    </div>
                </div>
                <a class="dropdown-item" href="profile.html">My Profile</a>
                
                {% if user.is_authenticated %}
                 <a class="dropdown-item" href="{% url 'users:user-logout' %}">Logout</a>
                {% endif %}
                    
            </div>
        </li>

    </ul>

</div>

src/templates/utils/message-alert.html
{% if messages %}
  <div class="container mt-3">
    {% for message in messages %}
      <div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'warning' %}alert-warning {% elif message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

src/templates/utils/settings-menu.html
<div class="settings-menu-links">
    <ul class="nav nav-tabs menu-tabs">
        <li class="nav-item {% if request.resolver_match.url_name == 'settings-home' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:settings-home' %}">General Settings</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'settings-fees' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:settings-fees' %}">Fee Installments</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'setting-sessions' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:setting-sessions' %}">Session Settings</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'setting-terms' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:setting-terms' %}">Term Settings</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'setting-exam-sessions' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:setting-exam-sessions' %}">Examination Sessions</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'toggle-marks-uploads' %}active{% endif %}">
            <a class="nav-link" href="{% url 'settings:toggle-marks-uploads' %}">Permissions</a>
        </li>
    </ul>
</div>

src/templates/utils/sidebar.html
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li class="submenu {% if section == 'admin-area'  %}active{% endif %}">
                    <a href="#"><i class="feather-grid"></i> <span> Dashboard</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'staff:admin-dashboard' %}" class="{% if request.path == '/'  %}active{% endif %}">Admin Dashboard</a></li>
                        
                        <li><a href="teacher-dashboard.html">Teachers Dashboard</a></li>
                        
                    </ul>
                </li>
                <li class="submenu {% if section == 'student-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-graduation-cap"></i> <span> Students</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:student-list' %}" class="{% if request.path == '/students/'  %}active{% endif %}">Student List</a></li>
                        <!-- <li><a href="student-details.html">Student View</a></li> -->
                        <li><a href="{% url 'students:student-add' %}" class="{% if request.resolver_match.url_name == 'student-add'  %}active{% endif %}">Student Add</a></li>
                        <li><a href="{% url 'students:student-dashboard' %}" class="{% if request.resolver_match.url_name == 'student-dashboard'  %}active{% endif %}">Student Dashboard</a></li>
                        
                        {% if student_detial_section %}
                            <li><a href="" class="active">Student View</a></li>
                        {% endif %}
                            
                    </ul>
                </li>
                <li class="submenu {% if section == 'teachers-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Teachers</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'teachers:teachers-list' %}" class="{% if request.path == '/teachers/'  %}active{% endif %}">Teacher List</a></li>
                        <!-- <li><a href="teacher-details.html">Teacher View</a></li> -->
                        <li><a href="{% url 'teachers:teachers-add' %}" class="{% if request.resolver_match.url_name == 'teachers-add'  %}active{% endif %}">Teacher Add</a></li>
                        <li><a href="{% url 'teachers:teacher-dashboard' %}" class="{% if request.resolver_match.url_name == 'teacher-dashboard'  %}active{% endif %}">Teacher Dashboard</a></li>
                        <!-- <li><a href="edit-teacher.html">Teacher Edit</a></li> -->
                    </ul>
                </li>
                <li class="submenu {% if section == 'class-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Classes</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <!-- <li><a href="{% url 'teachers:teachers-list' %}" class="{% if request.path == '/teachers/'  %}active{% endif %}">Teacher List</a></li> -->
                        <!-- <li><a href="teacher-details.html">Teacher View</a></li> -->
                        <li><a href="{% url 'class-list' %}" class="{% if request.resolver_match.url_name == 'class-list'  %}active{% endif %}">Classes</a></li>
                        <li><a href="{% url 'class-add' %}" class="{% if request.resolver_match.url_name == 'class-add'  %}active{% endif %}">Class Add</a></li>
                        <!-- <li><a href="edit-teacher.html">Teacher Edit</a></li> -->
                    </ul>
                </li>
                <li class="submenu {% if section == 'subjects-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'staff:subjects' %}">Subject List</a></li>
                        <li><a href="add-subject.html">Subject Add</a></li>
                        <li><a href="edit-subject.html">Subject Edit</a></li>
                    </ul>
                </li>
                <li class="{% if request.resolver_match.url_name == 'settings-home'  %}active{% endif %}">
                    <a href="{% url 'settings:settings-home' %} " ><i class="fas fa-cog"></i> <span>Settings</span></a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'marks'  %}active{% endif %}">
                    <a href="{% url 'students:marks' %} " ><i class="fas fa-certificate"></i> <span>Marks</span></a>
                </li>

                <li class="submenu {% if section == 'reports-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Reports</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'reports:reports' %}">Generate Reports</a></li>
                        <li><a href="add-subject.html">Subject Add</a></li>
                        <li><a href="edit-subject.html">Subject Edit</a></li>
                    </ul>
                </li>

                <li class="submenu {% if section == 'attendance-area'  %}active{% endif %}">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Attendance</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'attendance:take-attendance' %} ">Take Attendance</a></li>
                        <li><a href="{% url 'attendance:view-attendance' %}">View Attendance</a></li>
                    </ul>
                </li>



                <!-- <li class="submenu">
                    <a href="#"><i class="fas fa-certificate"></i> <span> Marks</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'students:marks' %}">Marks</a></li>
                        <li><a href="add-department.html">Department Add</a></li>
                        <li><a href="edit-department.html">Department Edit</a></li>
                    </ul>
                </li> -->
               
                {% comment %} <li class="submenu">
                    <a href="#"><i class="fas fa-clipboard"></i> <span> Invoices</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="invoices.html">Invoices List</a></li>
                        <li><a href="invoice-grid.html">Invoices Grid</a></li>
                        <li><a href="add-invoice.html">Add Invoices</a></li>
                        <li><a href="edit-invoice.html">Edit Invoices</a></li>
                        <li><a href="view-invoice.html">Invoices Details</a></li>
                        <li><a href="invoices-settings.html">Invoices Settings</a></li>
                    </ul>
                </li> {% endcomment %}
                <li class="menu-title">
                    <span>Management</span>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-users"></i> <span> Accounts</span> <span
                            class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'staff:create-admin' %}" class="{% if request.resolver_match.url_name == 'create-admin'  %}active{% endif %}">Add User</a></li>
                        <li><a href="{% url 'staff:list-admin' %}" class="{% if request.resolver_match.url_name == 'list-admin'  %}active{% endif %}">List Admin</a></li>
                    </ul>
                </li>
              
              
            </ul>
        </div>
    </div>
</div>